// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFeQ3OTOvFfxsFnLf1b_PyKz1Sxef4gJo',
    appId: '1:171359096707:web:900992882e26e7b6a230b6',
    messagingSenderId: '171359096707',
    projectId: 'autex-8e341',
    authDomain: 'autex-8e341.firebaseapp.com',
    storageBucket: 'autex-8e341.firebasestorage.app',
    measurementId: 'G-W5GQ8LYDZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv568flDTA292JdEL0UE9MZ9vF782jjwE',
    appId: '1:171359096707:android:86e1447e80c1fdb4a230b6',
    messagingSenderId: '171359096707',
    projectId: 'autex-8e341',
    storageBucket: 'autex-8e341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6sRGek8vu_of6ms6eP7aEtS1lVvtuNj0',
    appId: '1:171359096707:ios:7ede496bc43ddb05a230b6',
    messagingSenderId: '171359096707',
    projectId: 'autex-8e341',
    storageBucket: 'autex-8e341.firebasestorage.app',
    iosBundleId: 'com.autex.autex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6sRGek8vu_of6ms6eP7aEtS1lVvtuNj0',
    appId: '1:171359096707:ios:7ede496bc43ddb05a230b6',
    messagingSenderId: '171359096707',
    projectId: 'autex-8e341',
    storageBucket: 'autex-8e341.firebasestorage.app',
    iosBundleId: 'com.autex.autex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFeQ3OTOvFfxsFnLf1b_PyKz1Sxef4gJo',
    appId: '1:171359096707:web:debf674becd0d09ba230b6',
    messagingSenderId: '171359096707',
    projectId: 'autex-8e341',
    authDomain: 'autex-8e341.firebaseapp.com',
    storageBucket: 'autex-8e341.firebasestorage.app',
    measurementId: 'G-FMBKPY77GN',
  );
}
